document.writeln(typeof(100));
document.writeln(typeof(73.9));
document.writeln(typeof(NaN));
document.writeln(typeof("water"));
document.writeln(typeof (false));
document.writeln(typeof(9 != 11));
document.writeln("Orang" + "e" );
document.writeln("Orange" - "s" );
document.writeln( "4" + "8" );
document.writeln( "4" - "8" );
document.writeln( "name" + 3 );
document.writeln("name" - 3 );
document.writeln( 82 * "word");
document.writeln( 1 + "hello" );
document.writeln( "hello" + 1);
document.writeln( 1 + true);
document.writeln( "hello" + true );
document.writeln(  typeof (Infinity) );
document.writeln(  1 == '1'  );
document.writeln( 1 === '1'   );